Basic script updates

diff --git a/media-processing/yt-dl b/media-processing/yt-dl
--- a/media-processing/yt-dl
+++ b/media-processing/yt-dl
@@ -2,13 +2,18 @@
 # create an alias
 # source ~/.bash_aliases
 # alias yt='docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl'
-alias yt='sudo docker run --rm -u 0:0 -v $PWD:/data vimagick/youtube-dl'
+alias yt='docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl'
 
 # list all formats
 # $ yt -F %1%
 
 # download it
-yt %1%
+if [ -z "$1" ]; then
+  echo "Error: No URL provided."
+  exit 1
+fi
+
+yt "$1"
 
 # play it
 # $ vlc *-nVjsGKrE6E8.mp4
