New directory and files for podman containers

diff --git a/podman-setup/Plex-podman b/podman-setup/Plex-podman
--- a/podman-setup/Plex-podman
+++ b/podman-setup/Plex-podman
@@ -10,38 +10,52 @@
 
 ###################################### 
 ##The variables here will need to be adjusted for your installation
+#container_name="plex"
+
+container_user="plex"
 container_name="plex"
+container_longname="plex"
+container_path="lscr.io/linuxserver/plex:latest"
+
+#Basedir is for all of the volumes
 BaseDir=/media
 #####################################
 
 
 # Add the user if it doesn't exist 
-useradd $container_name || echo "User already exists."
+useradd $container_user || echo "User already exists."
 
 
+# Get the user and group ID for below
+container_uid=`id -u $container_user`
+container_gid=`id -g $container_user`
 
 # create the directory for the podman volumes if it doesn't exist
 
-if [ ! -d /home/$container_name ];then
-     if ! mkdir /home/$container_name; then  # Shorter version. Shell will complain if you p>
-     echo "Can't make dir: $container_name"
+if [ ! -d /home/$container_user ];then
+     if ! mkdir /home/$container_user; then  # Shorter version. Shell will complain if you p>
+     echo "Can't make dir: $container_user"
      fi
 fi
 
-# Get the user and group ID for below
-container_id="$(echo $newvar | awk -F "=" '{print $2}' | awk -F "(" '{print$1}')"
-container_grp="$(echo $newvar | awk -F "gid=" '{print $2}' | awk -F "(" '{print$1}')"
-
+# make the container user be the owner of it's own homedir
+if [ ! -d /home/$container_user ];then
+     if ! mkdir /home/$container_user ; then
+     echo "Can't make dir: /home/$container_user"
+     ## Set the owner and group to be the new ID for that directory you just made
+     chown -R $container_uid:$container_gid /home/$container_user
+     fi
+fi
 
 
 
 # Create the media directory if it doesn't exist
 
 if [ ! -d $BaseDir ];then
-     if ! mkdir $BaseDir; then  
+     if ! mkdir $BaseDir; then
      echo "Can't make dir: $BaseDir"
      ## Set the owner and group to be the new ID for that directory you just made
-     chown -R $container_id:$container_grp $basedir
+     chown -R $container_uid:$container_gid $basedir
      fi
 fi
 
@@ -52,22 +66,22 @@ if [ "$(podman ps -q -f name=$container_name)" ]; then
     echo "Container $container_name is running, nothing to do"
 
 else
-# if the container isn't running, remove it 
+# if the container isn't running, remove it
     echo "Container $container_name is not running."
     if [ "!$(podman container inspect $container_name > /dev/null 2>&1)" ]; then
-        
-        echo "$container_name is not running $(podman rm $container_name)"
+    echo "$container_name is not running $(podman rm $container_name)"
 
 #############################
-# it seems that podman run command doesn't like variables for PUID and PGID, 
+# it seems that podman run command doesn't like variables for PUID and PGID,
 # make them the same as the user you created above
 #
-# volume info is specific to each container, so that will need to be edited 
+# volume info is specific to each container, so that will need to be edited
 #############################
 # start the container
 podman run -d   --name=$container_name  --net=host   \
 -e PUID=1002   -e PGID=1002   -e TZ=Etc/UTC   -e VERSION=podman   \
 -e PLEX_CLAIM= `#optional`   \
+--replace \
 -v $BaseDir/config:/config:Z   \
 -v $BaseDir/music:/music:Z   \
 -v $BaseDir/MusicVideos:/MusicVideos:Z  \
@@ -80,7 +94,7 @@ podman run -d   --name=$container_name  --net=host   \
 --restart unless-stopped  \
 lscr.io/linuxserver/plex:latest
 
-      
+
     fi
 fi
 
